[workspace]
members = ["node", "parser", "example"]
resolver = "3"

[workspace.package]
version = "0.1.0"
publish = false
edition = "2024"
license = "MIT"

[workspace.dependencies]
node = { path = "./node" }
parser = { path = "./parser" }
thiserror = "2.0.16"
