[package]
name = "node"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true

[dev-dependencies]
pretty_assertions = "1.4.1"
rstest = "0.26.1"
